stages:
  run-learning:
    cmd: python main.py
    deps:
      - main.py
      - learning/
    outs:
      - logs/
  tune-model:
    cmd: python forecast_engine/hyperparameter_tuner.py
    deps:
      - forecast_engine/hyperparameter_tuner.py
      - learning/
    outs:
      - logs/tuning_results.jsonl
    params:
      - params.yaml: [tuning]
