tuning:
  learning_rate:
    type: float
    low: 0.0001
    high: 0.1
    log: true
  batch_size:
    type: int
    low: 16
    high: 128
  optimizer:
    type: categorical
    choices: [adam, sgd, rmsprop]
