# ...existing code from previous rule_fingerprint_expander.py...
from .reverse_rule_mapper import load_rule_fingerprints, validate_fingerprint_schema
# ...existing code from previous rule_fingerprint_expander.py...
